// Generated by gencpp from file rppg/RGB.msg
// DO NOT EDIT!


#ifndef RPPG_MESSAGE_RGB_H
#define RPPG_MESSAGE_RGB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rppg
{
template <class ContainerAllocator>
struct RGB_
{
  typedef RGB_<ContainerAllocator> Type;

  RGB_()
    : m_rgb()  {
    }
  RGB_(const ContainerAllocator& _alloc)
    : m_rgb(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _m_rgb_type;
  _m_rgb_type m_rgb;





  typedef boost::shared_ptr< ::rppg::RGB_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rppg::RGB_<ContainerAllocator> const> ConstPtr;

}; // struct RGB_

typedef ::rppg::RGB_<std::allocator<void> > RGB;

typedef boost::shared_ptr< ::rppg::RGB > RGBPtr;
typedef boost::shared_ptr< ::rppg::RGB const> RGBConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rppg::RGB_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rppg::RGB_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rppg::RGB_<ContainerAllocator1> & lhs, const ::rppg::RGB_<ContainerAllocator2> & rhs)
{
  return lhs.m_rgb == rhs.m_rgb;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rppg::RGB_<ContainerAllocator1> & lhs, const ::rppg::RGB_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rppg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rppg::RGB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rppg::RGB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rppg::RGB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rppg::RGB_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rppg::RGB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rppg::RGB_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rppg::RGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23c5d650889550da7f52653940412067";
  }

  static const char* value(const ::rppg::RGB_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23c5d650889550daULL;
  static const uint64_t static_value2 = 0x7f52653940412067ULL;
};

template<class ContainerAllocator>
struct DataType< ::rppg::RGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rppg/RGB";
  }

  static const char* value(const ::rppg::RGB_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rppg::RGB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] m_rgb\n"
;
  }

  static const char* value(const ::rppg::RGB_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rppg::RGB_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m_rgb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RGB_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rppg::RGB_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rppg::RGB_<ContainerAllocator>& v)
  {
    s << indent << "m_rgb[]" << std::endl;
    for (size_t i = 0; i < v.m_rgb.size(); ++i)
    {
      s << indent << "  m_rgb[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.m_rgb[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RPPG_MESSAGE_RGB_H
